from __future__ import annotations

STRING: int = 1
NUMBER: int = 37
DATETIME: int = 11
BINARY: int = 15
BOOLEAN: int = 5
INT: int = 3
CHAR: int = 1
VARCHAR: int = 1
NCHAR: int = 1
TEXT: int = 16
FLOAT: int = 37
NUMERIC: int = 37
DECIMAL: int = 37
CURRENCY: int = 7
TIMESTAMP: int = 11
CLOB: int = 16
BLOB: int = 15
SMALLINT: int = 2
DATE: int = 9
TIME: int = 10
String: int = 1
Integer: int = 3
SmallInteger: int = 2
Numeric: int = 37
Float: int = 37
DateTime: int = 11
Date: int = 9
Time: int = 10
Binary: int = 15
Blob: int = 15
Image: int = 15
Boolean: int = 5
BIT: int = 5
BIGINT: int = 25
DOUBLE_PRECISION: int = 37

