<?xml version="1.0" encoding="UTF-8"?>
<rng:grammar xmlns:rng="http://relaxng.org/ns/structure/1.0"
             datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">

    <!-- anonymous15 -->
    <rng:define name="css-height">
        <rng:data type="string">
            <rng:param name="pattern">\d+(%|px|pt|em)?</rng:param>
        </rng:data>
    </rng:define>

    <!-- anonymous21 -->
    <rng:define name="css-width">
        <rng:data type="string">
            <rng:param name="pattern">(\*)|(\d+(%|px|em)?)</rng:param>
        </rng:data>
    </rng:define>

    <rng:define name="service-attr">
        <rng:attribute name="name">
            <rng:data type="string"/>
        </rng:attribute>
        <rng:attribute name="service">
            <rng:data type="string"/>
        </rng:attribute>
        <rng:attribute name="title">
            <rng:data type="string"/>
        </rng:attribute>
    </rng:define>

    <rng:define name="menu-attr">
        <rng:attribute name="name">
            <rng:data type="string"/>
        </rng:attribute>
        <rng:attribute name="title">
            <rng:data type="string"/>
        </rng:attribute>
        <rng:optional>
            <rng:attribute name="icon">
                <rng:data type="string"/>
            </rng:attribute>
        </rng:optional>
        <rng:optional>
            <rng:attribute name="key">
                <rng:data type="string"/>
            </rng:attribute>
        </rng:optional>
        <rng:optional>
            <rng:attribute name="hidden">
                <rng:data type="boolean"/>
            </rng:attribute>
        </rng:optional>
        <rng:optional>
            <rng:attribute name="mode">
                <rng:choice>
                    <rng:value type="string">desktop</rng:value>
                    <rng:value type="string">mobile</rng:value>
                </rng:choice>
            </rng:attribute>
        </rng:optional>
        <rng:optional>
            <rng:attribute name="icon-background">
                <rng:choice>
                    <rng:choice>
                        <rng:value type="string">pink</rng:value>
                        <rng:value type="string">green</rng:value>
                        <rng:value type="string">bluegrey</rng:value>
                        <rng:value type="string">deeporange</rng:value>
                        <rng:value type="string">lime</rng:value>
                        <rng:value type="string">yellow</rng:value>
                        <rng:value type="string">black</rng:value>
                        <rng:value type="string">violet</rng:value>
                        <rng:value type="string">teal</rng:value>
                        <rng:value type="string">amber</rng:value>
                        <rng:value type="string">lightgreen</rng:value>
                        <rng:value type="string">brown</rng:value>
                        <rng:value type="string">deeppurple</rng:value>
                        <rng:value type="string">cyan</rng:value>
                        <rng:value type="string">grey</rng:value>
                        <rng:value type="string">red</rng:value>
                        <rng:value type="string">orange</rng:value>
                        <rng:value type="string">blue</rng:value>
                        <rng:value type="string">lightblue</rng:value>
                        <rng:value type="string">white</rng:value>
                        <rng:value type="string">olive</rng:value>
                        <rng:value type="string">purple</rng:value>
                        <rng:value type="string">indigo</rng:value>
                    </rng:choice>
                    <rng:data type="string">
                        <rng:param name="pattern">#[\dA-Fa-f]{6}([\dA-Fa-f][\dA-Fa-f])?</rng:param>
                    </rng:data>
                </rng:choice>
            </rng:attribute>
        </rng:optional>
        <rng:optional>
            <rng:attribute name="action">
                <rng:data type="string"/>
            </rng:attribute>
        </rng:optional>
        <rng:optional>
            <rng:attribute name="order">
                <rng:data type="string"/>
            </rng:attribute>
        </rng:optional>
        <rng:optional>
            <rng:attribute name="left">
                <rng:data type="boolean"/>
            </rng:attribute>
        </rng:optional>
        <rng:optional>
            <rng:attribute name="hidden">
                <rng:data type="boolean"/>
            </rng:attribute>
        </rng:optional>
        <rng:optional>
            <rng:attribute name="tag">
                <rng:data type="string"/>
            </rng:attribute>
        </rng:optional>
        <rng:optional>
            <rng:attribute name="tag-count">
                <rng:data type="boolean"/>
            </rng:attribute>
        </rng:optional>
        <rng:optional>
            <rng:attribute name="tag-get">
                <rng:data type="string"/>
            </rng:attribute>
        </rng:optional>
        <rng:optional>
            <rng:attribute name="tag-style">
                <rng:choice>
                    <rng:value type="string">important</rng:value>
                    <rng:value type="string">inverse</rng:value>
                    <rng:value type="string">default</rng:value>
                    <rng:value type="string">success</rng:value>
                    <rng:value type="string">warning</rng:value>
                    <rng:value type="string">info</rng:value>
                </rng:choice>
            </rng:attribute>
        </rng:optional>
    </rng:define>

    <rng:define name="menuitem">
        <rng:element name="item">
            <rng:ref name="menu-attr"/>
            <rng:zeroOrMore>
                <rng:choice>
                    <rng:text/>
                    <rng:ref name="menuitem"/>
                </rng:choice>
            </rng:zeroOrMore>
        </rng:element>
    </rng:define>

    <rng:define name="menu">
        <rng:element name="menu">
            <rng:attribute name="name"/>
            <rng:oneOrMore>
                <rng:choice>
                    <rng:text/>
                    <rng:ref name="menuitem"/>
                </rng:choice>
            </rng:oneOrMore>
        </rng:element>
    </rng:define>

    <rng:define name="view-attr">
        <rng:attribute name="type">
            <rng:choice>
                <rng:value type="string">card</rng:value>
                <rng:value type="string">form</rng:value>
                <rng:value type="string">grid</rng:value>
                <rng:value type="string">dashboard</rng:value>
            </rng:choice>
        </rng:attribute>
        <rng:attribute name="name">
            <rng:data type="string"/>
        </rng:attribute>
    </rng:define>

    <rng:define name="action-attr">
        <rng:attribute name="name">
            <rng:data type="string"/>
        </rng:attribute>
        <rng:attribute name="service">
            <rng:data type="string"/>
        </rng:attribute>
        <rng:attribute name="title">
            <rng:data type="string"/>
        </rng:attribute>
        <rng:attribute name="type">
            <rng:choice>
                <rng:value type="string">card</rng:value>
                <rng:value type="string">form</rng:value>
                <rng:value type="string">grid</rng:value>
                <rng:value type="string">dashboard</rng:value>
            </rng:choice>
        </rng:attribute>
        <rng:attribute name="definition">
            <rng:data type="string"/>
        </rng:attribute>
        <rng:oneOrMore>
            <rng:element name="view">
                <rng:ref name="view-attr"/>
            </rng:element>
        </rng:oneOrMore>
    </rng:define>

    <rng:define name="action-view">
        <rng:element name="action-view">
            <rng:oneOrMore>
                <rng:element name="action">
                    <rng:ref name="action-attr"/>
                </rng:element>
            </rng:oneOrMore>
        </rng:element>
    </rng:define>

    <rng:define name="artanis_data">
        <rng:element name="artanis">
            <rng:oneOrMore>
                <rng:choice>
                    <rng:ref name="menu"/>
                    <rng:ref name="action-view"/>
                </rng:choice>
            </rng:oneOrMore>
        </rng:element>
    </rng:define>

    <rng:start>
        <rng:ref name="artanis_data"/>
    </rng:start>
</rng:grammar>
