{'action_view': {'cmn010': {'defkind': 'action',
                            'name': 'cmn010',
                            'service': 'cmn010',
                            'title': 'Addresses',
                            'type': 'grid',
                            'views': [{'name': 'cmn010-cards', 'type': 'card'},
                                      {'name': 'cmn010-form', 'type': 'form'},
                                      {'name': 'cmn010-grid', 'type': 'grid'},
                                      {'name': 'cmn010-dashboard',
                                       'type': 'dashboard'}]},
                 'cmn020': {'defkind': 'action',
                            'name': 'cmn020',
                            'service': 'cmn020',
                            'title': 'States',
                            'type': 'grid',
                            'views': [{'name': 'cmn020-cards', 'type': 'card'},
                                      {'name': 'cmn020-form', 'type': 'form'},
                                      {'name': 'cmn020-grid', 'type': 'grid'},
                                      {'name': 'cmn010-dashboard',
                                       'type': 'dashboard'}]}},
 'menu_definition': {'__beacukai_menu__': [{'icon': 'foundation.png',
                                            'name': 'base_foundation',
                                            'order': 100,
                                            'title': 'System Foundation'},
                                           {'icon': 'basic_data.png',
                                            'name': 'common_data',
                                            'order': 100,
                                            'parent': 'base_foundation',
                                            'title': 'Common Basic Data'},
                                           {'action': 'cmn010',
                                            'key': 'cmn010',
                                            'name': 'base_adresses',
                                            'order': 100,
                                            'parent': 'common_data',
                                            'title': 'Addresses'},
                                           {'action': 'cmn020',
                                            'key': 'cmn020',
                                            'name': 'base_states',
                                            'order': 100,
                                            'parent': 'common_data',
                                            'title': 'States'}],
                     '__default_menu__': [{'icon': 'foundation.png',
                                           'name': 'base_foundation',
                                           'order': 100,
                                           'title': 'System Foundation'},
                                          {'icon': 'basic_data.png',
                                           'name': 'common_data',
                                           'order': 100,
                                           'parent': 'base_foundation',
                                           'title': 'Common Basic Data'},
                                          {'action': 'cmn010',
                                           'key': 'cmn010',
                                           'name': 'base_adresses',
                                           'order': 100,
                                           'parent': 'common_data',
                                           'title': 'Addresses'},
                                          {'action': 'cmn020',
                                           'key': 'cmn020',
                                           'mode': 'desktop',
                                           'name': 'base_states',
                                           'order': 100,
                                           'parent': 'common_data',
                                           'title': 'States'},
                                          {'icon': 'sales.png',
                                           'name': 'sales_module',
                                           'order': 200,
                                           'title': 'Sales Module'},
                                          {'action': 'sales_orders',
                                           'key': 'sales_orders',
                                           'name': 'sales_orders',
                                           'order': 100,
                                           'parent': 'sales_module',
                                           'title': 'Sales Orders'},
                                          {'action': 'sales_invoices',
                                           'key': 'sales_invoices',
                                           'name': 'sales_invoices',
                                           'order': 200,
                                           'parent': 'sales_module',
                                           'title': 'Sales Invoices'}]}}
