[{'defkind': 'grid',
  'items': [{'background': 'warning',
             'defkind': 'hilite',
             'if': '(endOfValidityDate != null) && ($moment(endOfValidityDate) '
                   '< $moment(todayDate)) && (statusSelect == 3)'},
            {'background': 'danger',
             'defkind': 'hilite',
             'if': '(endOfValidityDate != null) && ($moment(endOfValidityDate) '
                   '< $moment(todayDate)) && (statusSelect == 2)'},
            {'defkind': 'field', 'hidden': True, 'name': 'endOfValidityDate'},
            {'defkind': 'field', 'name': 'saleOrderSeq', 'width': '120'},
            {'defkind': 'field',
             'form-view': 'company-form',
             'grid-view': 'company-grid',
             'name': 'company'},
            {'defkind': 'field', 'name': 'stockLocation'},
            {'defkind': 'field',
             'form-view': 'trading-name-form',
             'grid-view': 'trading-name-grid',
             'name': 'tradingName'},
            {'defkind': 'field',
             'form-view': 'partner-form',
             'grid-view': 'partner-grid',
             'name': 'clientPartner',
             'x-image-field': 'picture'},
            {'defkind': 'field', 'name': 'externalReference'},
            {'defkind': 'field', 'name': 'creationDate'},
            {'aggregate': 'sum',
             'defkind': 'field',
             'name': 'exTaxTotal',
             'x-scale': 'currency.numberOfDecimals'},
            {'aggregate': 'sum',
             'defkind': 'field',
             'name': 'inTaxTotal',
             'x-scale': 'currency.numberOfDecimals'},
            {'defkind': 'field',
             'form-view': 'currency-form',
             'grid-view': 'currency-grid',
             'name': 'currency'},
            {'defkind': 'field',
             'hidden': True,
             'name': 'currency.numberOfDecimals'},
            {'defkind': 'field',
             'name': 'statusSelect',
             'widget': 'single-select'},
            {'defkind': 'field', 'name': 'lastReminderDate'},
            {'defkind': 'field', 'name': 'lastReminderComments'},
            {'defkind': 'button',
             'icon': 'printer',
             'name': 'printBtn',
             'onClick': 'action-sale-order-method-show-sale-order',
             'title': 'Print'},
            {'defkind': 'button',
             'icon': 'envelope-fill',
             'name': 'sendByEmailBtn',
             'onClick': 'action-send-by-email-with-template',
             'title': 'Send email'}],
  'menubar': [{'defkind': 'menu',
               'icon': 'wrench',
               'items': [{'action': 'action-sale-order-method-convert-selected-lines-to-merge-lines',
                          'defkind': 'item',
                          'name': 'mergeQuotationsItem',
                          'title': 'Merge quotations'},
                         {'action': 'action-view-open-quotation-lines',
                          'defkind': 'item',
                          'name': 'seeQuotationLinesItem',
                          'title': 'See quotation lines'}],
               'name': 'saleOrderToolsMenu',
               'showTitle': True,
               'title': 'Tools'}],
  'name': 'sale-order-quotation-grid',
  'orderBy': '-creationDate',
  'service': 'com.axelor.apps.sale.db.SaleOrder',
  'title': 'Sale quotations',
  'toolbar': [{'defkind': 'button',
               'icon': 'printer',
               'name': 'printBtn',
               'onClick': 'action-sale-order-method-show-sale-order',
               'title': 'Print'}]},
 {'defkind': 'grid',
  'items': [{'background': 'warning',
             'defkind': 'hilite',
             'if': '(endOfValidityDate != null) && ($moment(endOfValidityDate) '
                   '< $moment(todayDate)) && (statusSelect == 3)'},
            {'background': 'danger',
             'defkind': 'hilite',
             'if': '(endOfValidityDate != null) && ($moment(endOfValidityDate) '
                   '< $moment(todayDate)) && (statusSelect == 2)'},
            {'defkind': 'field', 'hidden': True, 'name': 'endOfValidityDate'},
            {'defkind': 'field', 'name': 'saleOrderSeq', 'width': '120'},
            {'defkind': 'field',
             'form-view': 'company-form',
             'grid-view': 'company-grid',
             'name': 'company'},
            {'defkind': 'field', 'name': 'stockLocation'},
            {'defkind': 'field',
             'form-view': 'trading-name-form',
             'grid-view': 'trading-name-grid',
             'name': 'tradingName'},
            {'defkind': 'field',
             'form-view': 'partner-form',
             'grid-view': 'partner-grid',
             'name': 'clientPartner',
             'x-image-field': 'picture'},
            {'defkind': 'field', 'name': 'externalReference'},
            {'defkind': 'field', 'name': 'confirmationDateTime'},
            {'aggregate': 'sum',
             'defkind': 'field',
             'name': 'exTaxTotal',
             'x-scale': 'currency.numberOfDecimals'},
            {'aggregate': 'sum',
             'defkind': 'field',
             'name': 'inTaxTotal',
             'x-scale': 'currency.numberOfDecimals'},
            {'aggregate': 'sum',
             'defkind': 'field',
             'hidden': True,
             'name': 'amountInvoiced',
             'x-scale': 'currency.numberOfDecimals'},
            {'defkind': 'field',
             'form-view': 'currency-form',
             'grid-view': 'currency-grid',
             'name': 'currency'},
            {'defkind': 'field',
             'hidden': True,
             'name': 'currency.numberOfDecimals'},
            {'defkind': 'field', 'name': 'deliveryState'},
            {'defkind': 'field',
             'name': 'statusSelect',
             'widget': 'single-select'},
            {'defkind': 'field', 'name': 'salespersonUser'},
            {'defkind': 'button',
             'icon': 'printer',
             'name': 'printBtn',
             'onClick': 'action-sale-order-method-show-sale-order',
             'title': 'Print'},
            {'defkind': 'button',
             'icon': 'envelope-fill',
             'name': 'sendByEmailBtn',
             'onClick': 'action-send-by-email-with-template',
             'title': 'Send email'}],
  'menubar': [{'defkind': 'menu',
               'icon': 'wrench',
               'items': [{'action': 'action-view-open-sale-order-lines',
                          'defkind': 'item',
                          'name': 'seeSaleOrderLinesItem',
                          'title': 'See sale orders lines'}],
               'name': 'saleOrderToolsMenu',
               'showTitle': True,
               'title': 'Tools'}],
  'name': 'sale-order-grid',
  'orderBy': '-creationDate',
  'service': 'com.axelor.apps.sale.db.SaleOrder',
  'title': 'Sale orders',
  'toolbar': [{'defkind': 'button',
               'icon': 'printer',
               'name': 'printBtn',
               'onClick': 'action-sale-order-method-show-sale-order',
               'title': 'Print'}]},
 {'defkind': 'grid',
  'items': [{'defkind': 'field', 'name': 'saleOrderSeq', 'width': '120'},
            {'defkind': 'field',
             'form-view': 'company-form',
             'grid-view': 'company-grid',
             'name': 'company'},
            {'defkind': 'field',
             'form-view': 'trading-name-form',
             'grid-view': 'trading-name-grid',
             'name': 'tradingName'},
            {'defkind': 'field', 'name': 'externalReference'},
            {'defkind': 'field', 'name': 'creationDate'},
            {'defkind': 'field', 'hidden': True, 'name': 'currency'},
            {'defkind': 'field',
             'hidden': True,
             'name': 'currency.numberOfDecimals'},
            {'aggregate': 'sum',
             'defkind': 'field',
             'name': 'exTaxTotal',
             'x-scale': 'currency.numberOfDecimals'},
            {'aggregate': 'sum',
             'defkind': 'field',
             'name': 'inTaxTotal',
             'x-scale': 'currency.numberOfDecimals'},
            {'defkind': 'field',
             'name': 'statusSelect',
             'widget': 'single-select'},
            {'defkind': 'button',
             'icon': 'printer',
             'name': 'printBtn',
             'onClick': 'action-sale-order-method-show-sale-order',
             'title': 'Print'},
            {'defkind': 'button',
             'icon': 'envelope-fill',
             'name': 'sendByEmailBtn',
             'onClick': 'action-send-by-email-with-template',
             'title': 'Send email'}],
  'menubar': [{'defkind': 'menu',
               'icon': 'wrench',
               'items': [{'action': 'action-view-open-sale-order-lines',
                          'defkind': 'item',
                          'name': 'seeSaleOrderLinesItem',
                          'title': 'See sale orders lines'}],
               'name': 'saleOrderToolsMenu',
               'showTitle': True,
               'title': 'Tools'}],
  'name': 'sale-order-partner-grid',
  'orderBy': '-creationDate',
  'service': 'com.axelor.apps.sale.db.SaleOrder',
  'title': 'Sale orders',
  'toolbar': [{'defkind': 'button',
               'icon': 'printer',
               'name': 'printBtn',
               'onClick': 'action-sale-order-method-show-sale-order',
               'title': 'Print'}]},
 {'defkind': 'grid',
  'items': [{'defkind': 'field', 'name': 'saleOrderSeq', 'width': '120'},
            {'defkind': 'field',
             'form-view': 'company-form',
             'grid-view': 'company-grid',
             'name': 'company'},
            {'defkind': 'field',
             'form-view': 'trading-name-form',
             'grid-view': 'trading-name-grid',
             'name': 'tradingName'},
            {'defkind': 'field', 'name': 'externalReference'},
            {'defkind': 'field', 'name': 'creationDate'},
            {'defkind': 'field', 'hidden': True, 'name': 'currency'},
            {'defkind': 'field',
             'hidden': True,
             'name': 'currency.numberOfDecimals'},
            {'aggregate': 'sum',
             'defkind': 'field',
             'name': 'exTaxTotal',
             'x-scale': 'currency.numberOfDecimals'},
            {'aggregate': 'sum',
             'defkind': 'field',
             'name': 'inTaxTotal',
             'x-scale': 'currency.numberOfDecimals'},
            {'aggregate': 'sum',
             'defkind': 'field',
             'name': 'inTaxTotalRemainingToOrder',
             'x-scale': 'currency.numberOfDecimals'},
            {'defkind': 'field',
             'name': 'statusSelect',
             'widget': 'single-select'},
            {'defkind': 'button',
             'icon': 'printer',
             'name': 'printBtn',
             'onClick': 'action-sale-order-method-show-sale-order',
             'title': 'Print'},
            {'defkind': 'button',
             'icon': 'envelope-fill',
             'name': 'sendByEmailBtn',
             'onClick': 'action-send-by-email-with-template',
             'title': 'Send email'}],
  'name': 'sale-order-partner-quotation-grid',
  'orderBy': '-creationDate',
  'service': 'com.axelor.apps.sale.db.SaleOrder',
  'title': 'Sale orders'},
 {'defkind': 'grid',
  'items': [{'background': 'warning',
             'defkind': 'hilite',
             'if': '(endOfValidityDate != null) && ($moment(endOfValidityDate) '
                   '< $moment(todayDate)) && (statusSelect == 3)'},
            {'background': 'danger',
             'defkind': 'hilite',
             'if': '(endOfValidityDate != null) && ($moment(endOfValidityDate) '
                   '< $moment(todayDate)) && (statusSelect == 2)'},
            {'defkind': 'field', 'hidden': True, 'name': 'endOfValidityDate'},
            {'defkind': 'field', 'name': 'saleOrderSeq', 'width': '120'},
            {'defkind': 'field', 'name': 'creationDate'},
            {'aggregate': 'sum',
             'defkind': 'field',
             'name': 'exTaxTotal',
             'x-scale': 'currency.numberOfDecimals'},
            {'aggregate': 'sum',
             'defkind': 'field',
             'name': 'inTaxTotal',
             'x-scale': 'currency.numberOfDecimals'},
            {'defkind': 'field',
             'form-view': 'currency-form',
             'grid-view': 'currency-grid',
             'name': 'currency'},
            {'defkind': 'field',
             'hidden': True,
             'name': 'currency.numberOfDecimals'},
            {'defkind': 'field',
             'name': 'statusSelect',
             'widget': 'single-select'},
            {'defkind': 'button',
             'icon': 'printer',
             'name': 'printBtn',
             'onClick': 'action-sale-order-method-show-sale-order',
             'title': 'Print'},
            {'defkind': 'button',
             'icon': 'envelope-fill',
             'name': 'sendByEmailBtn',
             'onClick': 'action-send-by-email-with-template',
             'title': 'Send email'}],
  'name': 'sale-order-opportunity-grid',
  'orderBy': '-creationDate',
  'service': 'com.axelor.apps.sale.db.SaleOrder',
  'title': 'Sale quotations'},
 {'colorBy': 'statusSelect',
  'defkind': 'calendar',
  'editable': False,
  'eventLength': 24,
  'eventStart': 'creationDate',
  'items': [{'colorBy': 'statusSelect',
             'defkind': 'calendar',
             'editable': False,
             'eventLength': 24,
             'eventStart': 'creationDate',
             'mode': 'month',
             'name': 'sale-order-calendar',
             'service': 'com.axelor.apps.sale.db.SaleOrder',
             'title': 'Sale quotations/orders'}],
  'mode': 'month',
  'name': 'sale-order-calendar',
  'service': 'com.axelor.apps.sale.db.SaleOrder',
  'title': 'Sale quotations/orders'},
 {'defkind': 'form',
  'items': [{'canEdit': 'false',
             'canNew': False,
             'colSpan': '12',
             'defkind': 'panel-related',
             'domain': 'self.statusSelect = 1',
             'field': '$saleOrderToMerge',
             'form-view': 'sale-order-form',
             'grid-view': 'sale-order-grid',
             'items': [],
             'name': 'saleOrderToMergePanel',
             'target': 'com.axelor.apps.sale.db.SaleOrder',
             'title': 'Sale orders to merge'},
            {'defkind': 'panel',
             'items': [{'defkind': 'button',
                        'name': 'generateMergedSaleOrderBtn',
                        'onClick': 'action-validate-sale-order-check-selection,action-group-sale-order-merge-action',
                        'title': 'Merge into single sale order'}],
             'name': 'actionsPanel',
             'sidebar': True,
             'title': 'Actions'}],
  'name': 'sale-order-merge-form',
  'service': 'com.axelor.utils.db.Wizard',
  'title': 'Merge sale orders',
  'width': 'large'},
 {'defkind': 'form',
  'items': [{'canEdit': 'false',
             'canNew': False,
             'colSpan': '12',
             'defkind': 'panel-related',
             'domain': 'self.statusSelect = 1',
             'field': '$saleQuotationToMerge',
             'form-view': 'sale-order-form',
             'grid-view': 'sale-order-quotation-grid',
             'items': [],
             'name': 'saleQuotationToMergePanel',
             'target': 'com.axelor.apps.sale.db.SaleOrder',
             'title': 'Quotations to merge'},
            {'defkind': 'panel',
             'items': [{'defkind': 'button',
                        'name': 'generateMergedSaleOrderBtn',
                        'onClick': 'action-validate-sale-quotation-check-selection,action-group-sale-order-merge-action',
                        'title': 'Merge into single quotation'}],
             'name': 'actionsPanel',
             'sidebar': True,
             'title': 'Actions'}],
  'name': 'sale-quotation-merge-form',
  'service': 'com.axelor.utils.db.Wizard',
  'title': 'Merge quotations',
  'width': 'large'},
 {'defkind': 'form',
  'items': [{'colOffset': '3',
             'colSpan': '6',
             'defkind': 'panel',
             'items': [{'colSpan': '12',
                        'defkind': 'button',
                        'name': 'confirmBtn',
                        'onClick': 'action-sale-order-method-merge-from-pop-up',
                        'title': 'Confirmer',
                        'width': '200px'},
                       {'colSpan': '12',
                        'defkind': 'button',
                        'name': 'confirmBtn',
                        'onClick': 'action-supplychain-stock-move-method-generate-invoice-from-pop-up',
                        'title': 'Confirmer',
                        'width': '200px'}],
             'name': 'mainPanel'}],
  'name': 'sale-order-merge-confirm-form',
  'onNew': 'action-record-load-dummy-field-confirm-merge-saleorder',
  'service': 'com.axelor.utils.db.Wizard',
  'title': 'Confirmation'},
 {'defkind': 'form',
  'items': [{'defkind': 'panel',
             'items': [{'colSpan': '4',
                        'defkind': 'button',
                        'name': 'createOrderFromTemplateBtn',
                        'onClick': 'action-sale-order-method-generate-order',
                        'title': 'Create Order from this Template'}],
             'name': 'mainPanel'}],
  'name': 'sale-order-template-wizard-form',
  'onNew': 'action-sale-order-attrs-template-deafult-currency,action-sale-order-method-fill-price-list',
  'service': 'com.axelor.utils.db.Wizard',
  'title': 'Create the quotation'},
 {'defkind': 'form',
  'items': [{'defkind': 'panel',
             'items': [{'colOffset': '4',
                        'colSpan': '4',
                        'defkind': 'button',
                        'name': 'cancelConfirmBtn',
                        'onClick': 'action-sale-order-cancel-reason-check,action-sale-order-method-confirm-cancel',
                        'title': 'Confirm cancellation'}],
             'name': 'mainPanel'}],
  'name': 'sale-order-cancel-wizard-form',
  'service': 'com.axelor.apps.sale.db.SaleOrder',
  'title': 'Cancellation confirmation'},
 {'defkind': 'form',
  'items': [{'defkind': 'panel-include',
             'items': [],
             'view': 'sale-order-form'}],
  'name': 'sale-order-form-wizard',
  'onLoad': 'action-group-sale-saleorder-onload',
  'onNew': 'action-sale-order-method-onnew,action-sale-order-method-create-order,action-sale-order-record-hide-discount',
  'service': 'com.axelor.apps.sale.db.SaleOrder',
  'title': 'Sale order'},
 {'defkind': 'form',
  'items': [{'defkind': 'panel-include',
             'items': [],
             'view': 'sale-order-form'}],
  'name': 'sale-order-form-partner',
  'onLoad': 'action-group-sale-saleorder-onload',
  'onNew': 'action-sale-order-method-onnew,action-group-partner-saleorder-onnew',
  'service': 'com.axelor.apps.sale.db.SaleOrder',
  'title': 'Sale order'}]
