{'actions': {'action-address-change-city': {'defkind': 'action-record',
                                            'items': [{'defkind': 'field',
                                                       'expr': '',
                                                       'if': '',
                                                       'name': 'country'},
                                                      {'defkind': 'field',
                                                       'expr': '',
                                                       'if': '',
                                                       'name': 'zip'},
                                                      {'defkind': 'field',
                                                       'expr': '',
                                                       'if': '',
                                                       'name': 'street'},
                                                      {'defkind': 'field',
                                                       'expr': '',
                                                       'if': '',
                                                       'name': 'townName'}],
                                            'name': 'action-address-change-city',
                                            'service': 'com.axelor.apps.base.db.Address'},
             'action-address-method-autocomplete-address': {'defkind': 'action-method',
                                                            'items': [{'class': 'cmn010',
                                                                       'defkind': 'call',
                                                                       'method': 'autocompleteAddress'}],
                                                            'name': 'action-address-method-autocomplete-address'},
             'action-address-record-change-streetName': {'defkind': 'action-record',
                                                         'items': [{'defkind': 'field',
                                                                    'expr': '',
                                                                    'if': '',
                                                                    'name': 'streetName'},
                                                                   {'defkind': 'field',
                                                                    'expr': '',
                                                                    'if': '',
                                                                    'name': 'streetName'},
                                                                   {'defkind': 'field',
                                                                    'expr': '',
                                                                    'if': '',
                                                                    'name': 'streetName'},
                                                                   {'defkind': 'field',
                                                                    'expr': '',
                                                                    'if': '',
                                                                    'name': 'city'},
                                                                   {'defkind': 'field',
                                                                    'expr': '',
                                                                    'if': '',
                                                                    'name': 'zip'},
                                                                   {'defkind': 'field',
                                                                    'expr': '',
                                                                    'if': '',
                                                                    'name': 'country'}],
                                                         'name': 'action-address-record-change-streetName',
                                                         'service': 'cmn010'},
             'action-address-record-clear-fields': {'defkind': 'action-record',
                                                    'items': [{'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'city'},
                                                              {'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'zip'},
                                                              {'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'postBox'},
                                                              {'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'streetName'},
                                                              {'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'street'},
                                                              {'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'buildingNumber'},
                                                              {'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'room'},
                                                              {'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'floor'},
                                                              {'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'department'},
                                                              {'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'subDepartment'},
                                                              {'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'buildingName'},
                                                              {'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'townName'},
                                                              {'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'townLocationName'},
                                                              {'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'districtName'},
                                                              {'defkind': 'field',
                                                               'expr': '',
                                                               'if': '',
                                                               'name': 'countrySubDivision'}],
                                                    'name': 'action-address-record-clear-fields',
                                                    'service': 'cmn010'},
             'action-address-validate-change-city': {'defkind': 'action-validate',
                                                     'items': [{'defkind': 'alert',
                                                                'if': '',
                                                                'message': 'City '
                                                                           'zip '
                                                                           'is '
                                                                           'different '
                                                                           'from '
                                                                           'address '
                                                                           'zip'}],
                                                     'name': 'action-address-validate-change-city'},
             'action-base-address-check-address-used': {'defkind': 'action-validate',
                                                        'items': [{'defkind': 'alert',
                                                                   'if': 'isUsed '
                                                                         '== '
                                                                         'true',
                                                                   'message': 'Be '
                                                                              'aware '
                                                                              'that '
                                                                              'the '
                                                                              'address '
                                                                              'is '
                                                                              'already '
                                                                              'in '
                                                                              'use '
                                                                              'on '
                                                                              'other '
                                                                              'documents, '
                                                                              'do '
                                                                              'you '
                                                                              'still '
                                                                              'want '
                                                                              'to '
                                                                              'modify '
                                                                              'it '
                                                                              '?'}],
                                                        'name': 'action-base-address-check-address-used'},
             'action-base-address-get-address-fields': {'defkind': 'action-method',
                                                        'items': [{'class': 'cmn010',
                                                                   'defkind': 'call',
                                                                   'method': 'getAddressMetaField'}],
                                                        'name': 'action-base-address-get-address-fields'},
             'action-base-address-method-create-partner-address': {'defkind': 'action-method',
                                                                   'items': [{'class': 'cmn010',
                                                                              'defkind': 'call',
                                                                              'method': 'createPartnerAddress'}],
                                                                   'name': 'action-base-address-method-create-partner-address'},
             'action-base-address-method-update-lat-long': {'defkind': 'action-method',
                                                            'items': [{'class': 'cmn010',
                                                                       'defkind': 'call',
                                                                       'method': 'updateLatLong'}],
                                                            'name': 'action-base-address-method-update-lat-long'},
             'action-base-address-method-view-direction': {'defkind': 'action-method',
                                                           'items': [{'class': 'cmn010',
                                                                      'defkind': 'call',
                                                                      'method': 'viewDirection'}],
                                                           'name': 'action-base-address-method-view-direction'},
             'action-base-address-method-view-map': {'defkind': 'action-method',
                                                     'items': [{'class': 'cmn010',
                                                                'defkind': 'call',
                                                                'method': 'viewMap'}],
                                                     'name': 'action-base-address-method-view-map'},
             'action-base-address-set-address-used': {'defkind': 'action-record',
                                                      'items': [{'defkind': 'field',
                                                                 'expr': 'call:com.axelor.apps.base.service.address.AddressService:checkAddressUsed(id)',
                                                                 'name': 'isUsed'}],
                                                      'name': 'action-base-address-set-address-used',
                                                      'service': 'cmn010'},
             'action-group-base-address-country-change': {'defkind': 'action-group',
                                                          'items': [{'defkind': 'action',
                                                                     'name': 'action-address-record-clear-fields'},
                                                                    {'defkind': 'action',
                                                                     'name': 'action-base-address-get-address-fields'}],
                                                          'name': 'action-group-base-address-country-change'},
             'action-group-base-address-onload': {'defkind': 'action-group',
                                                  'items': [{'defkind': 'action',
                                                             'name': 'action-base-address-get-address-fields'}],
                                                  'name': 'action-group-base-address-onload'},
             'action-group-base-address-onnnew': {'defkind': 'action-group',
                                                  'items': [{'defkind': 'action',
                                                             'name': 'default-address-record'},
                                                            {'defkind': 'action',
                                                             'name': 'action-base-address-get-address-fields'}],
                                                  'name': 'action-group-base-address-onnnew'},
             'action-group-base-address-onsave': {'defkind': 'action-group',
                                                  'items': [{'defkind': 'action',
                                                             'name': 'action-base-address-set-address-used'},
                                                            {'defkind': 'action',
                                                             'name': 'action-base-address-check-address-used'},
                                                            {'defkind': 'action',
                                                             'name': 'save'},
                                                            {'defkind': 'action',
                                                             'name': 'action-base-address-method-create-partner-address'},
                                                            {'defkind': 'action',
                                                             'name': 'action-base-address-method-update-lat-long'}],
                                                  'name': 'action-group-base-address-onsave'},
             'default-address-record': {'defkind': 'action-record',
                                        'items': [{'defkind': 'field',
                                                   'expr': '',
                                                   'if': '',
                                                   'name': 'country'},
                                                  {'defkind': 'field',
                                                   'expr': '',
                                                   'if': '',
                                                   'name': 'country'}],
                                        'name': 'default-address-record',
                                        'service': 'com.axelor.apps.base.db.Address'}},
 'search_filters': {'address-filters': {'defkind': 'search-filters',
                                        'items': [{'defkind': 'field',
                                                   'hidden': True,
                                                   'name': 'buildingNumber'},
                                                  {'defkind': 'field',
                                                   'hidden': True,
                                                   'name': 'street'},
                                                  {'defkind': 'field',
                                                   'hidden': True,
                                                   'name': 'streetName'},
                                                  {'defkind': 'field',
                                                   'hidden': True,
                                                   'name': 'certifiedOk'},
                                                  {'defkind': 'field',
                                                   'hidden': True,
                                                   'name': 'pickList'}],
                                        'name': 'address-filters',
                                        'service': 'cmn010',
                                        'title': 'Address filters'}},
 'views': {'cmn010-form': {'defkind': 'form',
                           'items': [{'defkind': 'panel-include',
                                      'items': [],
                                      'view': 'incl-address-main-panel-form'},
                                     {'defkind': 'panel',
                                      'items': [],
                                      'name': 'addressTypePanel'},
                                     {'colSpan': '12',
                                      'defkind': 'panel',
                                      'items': [],
                                      'name': 'actionsPanel',
                                      'sidebar': True,
                                      'title': 'Actions'}],
                           'name': 'cmn010-form',
                           'onCopy': 'action-group-base-address-onload',
                           'onLoad': 'action-group-base-address-onload',
                           'onNew': 'action-group-base-address-onnnew',
                           'onSave': 'action-group-base-address-onsave',
                           'service': 'cmn010',
                           'title': 'Address',
                           'width': 'large'},
           'cmn010-grid': {'defkind': 'grid',
                           'items': [{'defkind': 'field', 'name': 'fullName'},
                                     {'defkind': 'button',
                                      'icon': 'geo-alt-fill',
                                      'name': 'mapBtn',
                                      'onClick': 'action-base-address-method-view-map'},
                                     {'defkind': 'button',
                                      'icon': 'near_me',
                                      'name': 'directionsBtn',
                                      'onClick': 'action-base-address-method-view-direction'}],
                           'name': 'cmn010-grid',
                           'service': 'cmn010',
                           'title': 'Address list',
                           'toolbar': [{'defkind': 'button',
                                        'name': 'checkDuplicateBtn',
                                        'onClick': 'action-base-method-show-duplicate',
                                        'title': 'Check Duplicate'}]},
           'incl-address-main-panel-form': {'defkind': 'form',
                                            'items': [{'colSpan': '12',
                                                       'defkind': 'panel',
                                                       'items': [],
                                                       'name': 'mainPanel',
                                                       'title': 'Address '
                                                                'details'}],
                                            'name': 'incl-address-main-panel-form',
                                            'onLoad': 'action-group-base-address-onload',
                                            'onNew': 'action-group-base-address-onnnew',
                                            'onSave': 'action-group-base-address-onsave',
                                            'service': 'cmn010',
                                            'title': 'Address'}}}
