[{'defkind': 'grid',
  'items': [{'defkind': 'field', 'name': 'fullName'},
            {'defkind': 'button',
             'icon': 'geo-alt-fill',
             'name': 'mapBtn',
             'onClick': 'action-base-address-method-view-map'},
            {'defkind': 'button',
             'icon': 'near_me',
             'name': 'directionsBtn',
             'onClick': 'action-base-address-method-view-direction'}],
  'name': 'address-grid',
  'service': 'cmn010',
  'title': 'Address list',
  'toolbar': [{'defkind': 'button',
               'name': 'checkDuplicateBtn',
               'onClick': 'action-base-method-show-duplicate',
               'title': 'Check Duplicate'}]},
 {'defkind': 'form',
  'items': [{'defkind': 'panel-include',
             'items': [],
             'view': 'incl-address-main-panel-form'},
            {'defkind': 'panel', 'items': [], 'name': 'addressTypePanel'},
            {'colSpan': '12',
             'defkind': 'panel',
             'items': [],
             'name': 'actionsPanel',
             'sidebar': True,
             'title': 'Actions'}],
  'name': 'address-form',
  'onCopy': 'action-group-base-address-onload',
  'onLoad': 'action-group-base-address-onload',
  'onNew': 'action-group-base-address-onnnew',
  'onSave': 'action-group-base-address-onsave',
  'service': 'cmn010',
  'title': 'Address',
  'width': 'large'},
 {'defkind': 'form',
  'items': [{'colSpan': '12',
             'defkind': 'panel',
             'items': [],
             'name': 'mainPanel',
             'title': 'Address details'}],
  'name': 'incl-address-main-panel-form',
  'onLoad': 'action-group-base-address-onload',
  'onNew': 'action-group-base-address-onnnew',
  'onSave': 'action-group-base-address-onsave',
  'service': 'cmn010',
  'title': 'Address'}]
