export type Size = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'

export type Color =
  | 'busana'
  | 'bosque'
  | 'bruma'
  | 'ciclon'
  | 'artanis'
  | 'primary'
  | 'busana-light'
  | 'bosque-light'
  | 'bruma-light'
  | 'ciclon-light'
  | 'artanis-light'
  | 'primary-light'
  | 'busana-dark'
  | 'bosque-dark'
  | 'bruma-dark'
  | 'ciclon-dark'
  | 'artanis-dark'
  | 'primary-dark'
